[package]
<<<<<<< HEAD
name = "yaci"
=======
name = "chip8"
>>>>>>> Initial structures for the emulator and instruction set.
version = "0.1.0"
authors = ["QualityHammer <agingllama@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
rand = "0.7"
sdl2 = "0.34"
=======
>>>>>>> Initial structures for the emulator and instruction set.
